# This action mirrors the cypress-realworld-app github repo into a Bitbucket Repo
# github.com/cypress-io/cypress-realworld-app -> bitbucket.org/cypress-io/cypress-realworld-app

name: Sync Bitbucket over SSH

on:
  push:
    branches:
      - develop

# set the BB_REPO variable to the destination bitbucket workspace name
env:
  BB_ROOT: git@bitbucket.org:cypress-io

jobs:
  syncbb:
    name: Synch from Github to Bitbucket using SSH
    runs-on: ubuntu-latest
    steps:
      - name: Clone the github repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BITBUCKET_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.BITBUCKET_KNOWN_HOSTS }}
          config: 
            Host bitbucket.org
              User git
              IdentityFile ~/.ssh/id_rsa
              IdentitiesOnly yes 

      - uses: franzdiebold/github-env-vars-action@v2
      - name: sync with bitbucket
        run: |
          cd $GITHUB_WORKSPACE
          # update the entire repo including tags/branches; prune out deleted items
          echo sync with $BB_ROOT/$CI_REPOSITORY_NAME
          git fetch --prune --unshallow 
          # make the bitbucket repo a remote called sync
          git remote add sync $BB_ROOT/$CI_REPOSITORY_NAME
          # force push the sync remote with all changes.
          git push --force --set-upstream -v --all sync